// Original explanatory lessons. Course offers live separately in courses.json.
const lessons=[];
const lesson=(slug,title,category,summary,visual,sections,exercise,quiz,sources)=>lessons.push({slug,title,category,summary,visual,sections,exercise,quiz,sources});
const section=(title,body,points=[],example='')=>({title,body,points,example});
lesson('market-foundations','How financial markets work','Foundations','Stocks, indices, derivatives and the mechanics behind a quoted price.','market',[
section('Start with the instrument, not the tip','A share represents an ownership interest in a company. A bond is a debt claim. An index is a calculation describing a basket of securities; it is not itself a share you can buy. Funds and derivatives can reference an index, but their structures and risks differ. A derivative obtains its value from an underlying asset or reference, with additional contract terms.', ['Stocks: business performance, valuation, liquidity and corporate-event risk.','Futures: a contract with obligations, margin and mark-to-market exposure.','Options: rights for buyers and obligations for sellers, with an expiry date.','Crypto and currencies: different market structures, custody arrangements and legal requirements.']),
section('Exchanges, brokers and the order book','An exchange brings together trading interests under its rules. A broker provides access; clearing and settlement determine how obligations are met. A screen price is usually a past transaction or a current quote, not a guaranteed execution price. The bid is a buying quote; the ask is a selling quote. Their gap is the spread.', ['NSE and BSE are Indian exchanges; their product and segment rules differ.','NIFTY 50, NIFTY Bank and SENSEX measure different baskets. A move in one does not mean every constituent moved.','Demat holdings, a cash trading account and a derivatives position are different records. Learn your broker’s workflow.'], 'Suppose the best bid is 99.90 and ask is 100.10. An immediate buy may transact near the ask, not at the last traded price of 100.00. Larger orders can reach worse prices deeper in the book.'),
section('Trading styles are time horizons, not skill levels','Scalping involves very short holding periods and many execution decisions. Intraday positions are normally opened and closed within the session. Swing and positional approaches hold longer and face overnight gaps and corporate events. Investing typically focuses on a longer-term ownership thesis. More frequent trading means costs and mistakes can accumulate faster.', ['Choose a study horizon before comparing charts. A daily chart and a five-minute chart answer different questions.','Market hours, settlement cycles, permitted order types and contract sizes may change; verify them with the exchange and broker.','A course, a chart pattern or a profitable example does not establish that trading is suitable for someone.']),
section('Build an information hierarchy','Use exchange announcements and company filings for corporate facts; use official economic releases for macro data. Separate a verified fact, an interpretation and an untested opinion. Social posts and screenshots can omit losses, costs or timing.', ['Ask: what instrument, what timestamp, which source and which assumptions?','Do not send money, account credentials, OTPs or remote access to someone promising guaranteed returns.','Understand costs, taxation and complaint channels before opening or using a real account.'])],
'Choose a fictional company and an index. Write three ways their risk differs. Then explain why buying a share is different from buying an option on it.',
{q:'Does a last-traded price guarantee the price of your next order?',options:['Yes, it is the promised fill','No; current quotes and liquidity affect execution','Only when a chart is rising'],answer:1,why:'A last trade is historical. Spread, available quantity and price movement determine the next execution.'},
[['NSE investor education','https://www.nseindia.com/static/invest/investors-home'],['SEBI investor caution','https://investor.sebi.gov.in/cautiontoinvestor.html']]);
lesson('candles-and-charts','Read candles without guessing','Foundations','OHLC, candle context, chart types, timeframes and common interpretation mistakes.','candles',[
section('Four prices, one interval','A standard candlestick describes the open, high, low and close over a chosen time interval. Its body joins open and close; its wick spans the extremes. If close is above open, the interval finished higher. That is a description of the past, not a forecast of the next candle.', ['A long body describes a larger net move relative to nearby candles.','A long wick shows an excursion away from the body; it does not identify who traded or prove manipulation.','A doji has open and close close together. Its importance depends on location and context.'], 'A candle with open 100, high 110, low 96 and close 106 rose by 6 units over the interval. Its range was 14 units. Neither value tells you what tomorrow will do.'),
section('Single- and multi-candle shapes','Hammer, shooting star and pin-bar names describe body-and-wick geometry. Engulfing patterns compare adjacent real bodies. An inside bar has its high and low within the previous bar’s range. Morning and evening stars use a three-candle sequence. Definitions vary slightly between textbooks and platforms.', ['Shape: describe the actual prices and relative sizes.','Location: ask whether it appears after a trend, at a zone or in random congestion.','Follow-through: study subsequent action without pretending the outcome was knowable in advance.','Failure: keep examples where the expected direction did not occur.']),
section('Timeframes change the story','A small upward candle can exist inside a large downward daily candle. Higher-timeframe context and a lower-timeframe observation are not contradictions. Match the timeframe to the question. A screenshot with no axis, timestamp or surrounding bars gives limited evidence.', ['Start with a higher-timeframe map, then inspect a lower-timeframe sequence.','Compare candles from the same data source and session definition.','A still-forming candle can change its shape before it closes.']),
section('Standard versus transformed charts','Line charts simplify prices, often using closes. OHLC bars and standard candles retain interval extremes. Heikin Ashi and some other chart styles transform prices; their displayed values may not be executable market prices. Logarithmic scales compare proportional moves while linear scales compare absolute changes.', ['Use standard, time-based OHLC when checking simple order-fill assumptions.','Do not infer a guaranteed entry price from a smoothed chart.','Use the pattern atlas as a vocabulary guide, not a buy/sell checklist.'])],
'Draw an up candle and a down candle with the same high and low. Mark open, close, body and wicks. Find a case where an attractive candle is followed by a move in the opposite direction.',
{q:'What does a long upper wick prove?',options:['A guaranteed decline','That an institution sold','Only that price traded above the body during that interval'],answer:2,why:'The wick records an extreme. It does not establish identity, motive or a future direction.'},
[['Fidelity technical-analysis learning','https://www.fidelity.com/learning-center/trading-investing/technical-analysis/using-technical-analysis'],['TradingView strategy assumptions','https://www.tradingview.com/pine-script-docs/concepts/strategies/']]);
lesson('price-action','Structure, zones and price action','Technical analysis','Higher highs, ranges, breakouts, retests, liquidity language and failed setups.','structure',[
section('Map the sequence before naming a pattern','An uptrend is often described by rising swing highs and lows; a downtrend by falling swing highs and lows. A range lacks sustained progress in either direction. The swing-identification rule matters: changing the lookback can change your labels. Record that rule before reviewing results.', ['Higher high / higher low: a sequence, not a guarantee of continuation.','Lower high / lower low: a sequence, not a reason by itself to short.','Break of structure and change of character are descriptive terms with non-universal definitions. Specify exactly which swing and which close you mean.']),
section('Support and resistance are areas','Support describes an area where prior declines met buying interest; resistance describes an area where advances met selling interest. Previous-session extremes, repeated turning points and round numbers can attract attention. None is an impenetrable wall.', ['Use a zone whose width reflects the instrument and timeframe.','Prior highs and lows are reference points, not certain pools of executable orders.','A broken resistance area may later behave as support, but a retest is not assured.'], 'In a fictional range from 100 to 110, a print at 110.20 is not automatically a durable breakout. Price can return below 110 before or after the candle closes.'),
section('Breakout, retest and failure','A breakout means price moved beyond a chosen boundary. A retest means it revisited that area. To study either, define what counts as a break, whether a close matters and how long the observation remains valid. A false breakout returns inside the prior structure instead of sustaining progress.', ['Context: preceding trend, volatility, nearby levels and scheduled events.','Evidence: closing location and volume relative to comparable periods.','Invalidation: a pre-written condition showing the idea no longer fits.','Alternative: the market can trend, range or reverse; consider more than one scenario.']),
section('Liquidity concepts without storytelling','Liquidity is the ability to transact size with limited price impact. Equal highs, equal lows and crowded stop locations are sometimes discussed as liquidity references. A quick move through a level is observable; claims about a particular institution intentionally hunting stops usually are not provable from candles alone.', ['A market-depth display is a snapshot and can change or cancel rapidly.','Order flow adds information, but does not eliminate uncertainty.','A setup is only a research hypothesis until costs, failures and out-of-sample behavior are examined.'])],
'Label ten swings using one fixed rule. Mark a range, a breakout, a successful retest and a failed breakout. Write the rule before looking at the later candles.',
{q:'What is a useful definition of a breakout for testing?',options:['It looks strong','A precise, recorded rule about a boundary and confirmation','Any touch of a round number'],answer:1,why:'A repeatable definition makes successes and failures comparable and reduces hindsight bias.'},
[['Support and resistance','https://zerodha.com/varsity/chapter/support-resistance/'],['NSE technical-analysis curriculum','https://www.nseindia.com/static/learn/self-study-ncfm-modules-intermediate-technical-analysis-module']]);
lesson('indicators-and-volume','Indicators, volume and confirmation','Technical analysis','Moving averages, RSI, VWAP, MACD, ATR and the limits of derived signals.','indicators',[
section('Indicators transform data; they do not create certainty','A simple moving average is an average over a lookback. An exponential moving average weights recent observations more heavily. Both lag the price data used to calculate them. Short lookbacks react faster and may be noisier; long lookbacks are smoother but slower.', ['Trend filters need explicit settings, data source and timeframe.','A crossover can whipsaw in a range.','Combining several price-derived indicators does not necessarily create independent confirmation.'], 'Closes of 98, 100, 102, 104 and 106 have a five-period simple average of 102. The average describes those five closes, not the next one.'),
section('Momentum and volatility answer different questions','RSI compares recent gains and losses through a bounded momentum calculation. High RSI is not automatically a sell signal; strong trends can remain strong. MACD compares exponential averages and a signal line. ATR summarizes true ranges, including gaps; it measures movement, not direction.', ['RSI: momentum context, not a universal reversal timer.','MACD: trend/momentum changes with lag and whipsaw risk.','ATR: compare the scale of movement; a high value does not say up or down.','Bollinger Bands: dispersion around an average, not guaranteed reversal barriers.']),
section('VWAP and volume need the right reference','VWAP is a volume-weighted average of traded prices over a chosen session or anchor. A price above VWAP is a relationship to that reference, not an automatic reason to buy. Volume counts traded activity; derivatives open interest counts outstanding contracts. The measures are not interchangeable.', ['Compare volume with similar times of day; opening activity naturally differs from midday.','A spot index is a calculation, not a single traded instrument with its own cash share volume. Know which volume series your chart uses.','Some currency feeds show tick activity rather than complete global traded volume.']),
section('Build a small, testable toolkit','Write down the job of each tool: context, volatility, participation or trigger. Avoid adding another indicator whenever a losing example appears. Change one research variable at a time and retain an untouched evaluation sample.', ['State the condition in plain language before coding it.','Include flat periods, gaps and event sessions in the review.','Check whether a signal repaints, uses future information or depends on an unfinished bar.'])],
'Calculate a five-period SMA manually, then compare it with a shorter average. Explain why an RSI reading of 75 cannot alone prove a reversal.',
{q:'What does ATR primarily describe?',options:['Direction of the next trade','The scale of price movement','Institutional buying'],answer:1,why:'ATR measures ranges, including gaps. It does not forecast direction.'},
[['Fidelity indicator guide','https://www.fidelity.com/learning-center/trading-investing/technical-analysis/using-technical-analysis'],['TradingView repainting concepts','https://www.tradingview.com/pine-script-docs/concepts/repainting/']]);
lesson('orders-and-execution','Orders, spreads and execution risk','Foundations','Why a correct idea can still produce a different fill or a larger loss.','orders',[
section('Market and limit orders make different trade-offs','A market order prioritizes execution at available prices; its fill price is not guaranteed. A limit order restricts the worst acceptable price but may remain unfilled or fill only partly. Availability and exact handling depend on the venue, instrument and broker.', ['A buy limit cannot execute above its limit under normal order rules, but it might not execute at all.','Displayed quantity can disappear before your order reaches the venue.','A large market order may consume several price levels.']),
section('A stop is a trigger, not insurance','A stop order activates according to its trigger conditions. A stop-market can fill far from the trigger during a gap or thin liquidity. A stop-limit adds a price boundary but may fail to close the position. Order types and segment restrictions differ; confirm current broker and exchange rules.', ['A target is a planned exit level, often implemented using a limit order; it is not a guaranteed profit.','A stop placed in software may behave differently from an exchange-held order.','Know what happens after a disconnection, rejection, partial fill or exchange halt.'], 'An example position bought at 100 has a stop trigger at 98. If the next available bid is 95 after a gap, a stop-market could execute near 95. The planned 2-unit risk was not a maximum-loss guarantee.'),
section('Friction belongs in every example','Net outcome differs from a chart’s entry-to-exit move. Brokerage, exchange levies, taxes, the bid–ask spread, slippage and funding or borrowing charges may apply. Rules vary by instrument and can change. Use official schedules and a qualified tax professional for personal tax treatment.', ['Estimate costs before evaluating a strategy, then stress-test worse costs.','Do not count an unfilled limit order as a successful trade in a backtest.','Track rejection and partial-fill handling in a paper execution checklist.']),
section('Make the platform part of the learning plan','Use a watchlist, a clear layout and alerts whose trigger you understand. Learn position versus order views, quantity units, validity, leverage settings and the broker’s square-off policies. Two similar-looking tickets can have very different consequences.', ['Check symbol, exchange, expiry, quantity, order type and price before confirming any real order.','Paper trading is for learning mechanics; it may not reproduce queue position, emotional stress or true liquidity.','Never share credentials or give an unverified person remote control of an account.'])],
'Using only a fictional order ticket, write how you would detect a wrong symbol, a wrong expiry and a ten-times-too-large quantity. Compare a stop-market gap with an unfilled stop-limit.',
{q:'Which order guarantees both your chosen price and execution?',options:['Market order','Limit order','Neither'],answer:2,why:'Market orders prioritize execution; limit orders constrain price but can remain unfilled. Neither guarantees both.'},
[['SEBI investor caution','https://investor.sebi.gov.in/cautiontoinvestor.html'],['NSE investor education','https://www.nseindia.com/static/invest/investors-home']]);
lesson('risk-and-psychology','Risk, position size and the thinking trap','Risk & process','Plan uncertain outcomes, understand drawdowns and build a review routine.','risk',[
section('Translate an idea into a risk budget','A research plan specifies the instrument, entry assumption, invalidation, exit process and quantity. Position size connects a price move to a cash outcome. A small-looking percentage change can create a large loss when quantity or leverage is large. There is no universally safe risk percentage.', ['For a simple long cash-share example: planned risk per share = entry minus stop, plus an allowance for costs and slippage.','A model quantity is the whole-number risk budget divided by planned risk per share, subject to available cash.','Actual gaps, liquidity and execution can produce a larger loss than the planned amount.'], 'Fictional capital 100,000 and a study risk budget of 1,000 with 2.50 units of planned risk per share produce 400 shares before cash constraints. This is arithmetic, not a recommended allocation.'),
section('Reward-to-risk is not a probability','A 2:1 planned reward-to-risk ratio describes the distances to two assumed exits. It says nothing by itself about the frequency of reaching each. Expectancy combines the probability and size of wins and losses, less costs. An attractive average can conceal rare large losses.', ['Expectancy = win probability × average win − loss probability × average loss − average costs.','A 40% win rate with average win 200 and average loss 100 has gross expectancy 20 per trade; costs of 25 make it negative.','A 20% drawdown requires a 25% gain on the remaining capital to recover. Loss and recovery percentages use different bases.']),
section('Correlations and leverage change the picture','Several positions can express the same risk factor. Three bank stocks and a banking-index position may be more concentrated than four independent bets. Futures margin is collateral, not the maximum loss. Options spreads can have execution and settlement complications beyond a neat payoff diagram.', ['Stress-test a gap, a spread widening and a platform outage together.','Avoid funding a speculative plan with money needed for essential expenses or borrowing you cannot afford.','Daily stop rules and position limits are process controls, not loss guarantees.']),
section('Use a process that survives emotion','FOMO, revenge trading, anchoring and confirmation bias distort decisions. A trading journal should compare your written process with what happened, not merely celebrate profitable outcomes. A rule-breaking win is not evidence that the rule-breaking was sound.', ['Before: event calendar, relevant levels, written scenarios and no-trade conditions.','During: follow the plan, record changes and pause when judgment is impaired.','After: save both successes and failures, including avoided trades and execution mistakes.','Review a sample over time; one result does not identify skill.'])],
'Use the practice lab to compare planned risk with a gap that doubles the stop distance. Explain why four correlated positions may not diversify risk.',
{q:'After a 20% loss, what gain restores the original capital?',options:['20%','25%','40%'],answer:1,why:'80 × 1.25 = 100. Recovery is calculated on the smaller remaining balance.'},
[['SEBI investor caution','https://investor.sebi.gov.in/cautiontoinvestor.html']]);
lesson('options-foundations','Options: rights, obligations and expiry','Options','Calls, puts, premium, intrinsic value, time value and contract risk.','options',[
section('Understand the contract before the chart','A call gives its buyer a right under the contract to buy the underlying or receive the appropriate cash settlement. A put provides the corresponding selling right. The seller takes the obligation. Exercise style, expiry, underlying, multiplier and settlement method are part of the contract, not details to ignore.', ['A call buyer can benefit from upward movement, but time and volatility also affect the premium.','A put buyer can benefit from downward movement, subject to the same additional factors.','Bought options can expire worthless. Sellers face obligations, margin requirements and potentially very large losses.']),
section('Intrinsic value is not profit','At expiry, call intrinsic value per unit is max(underlying − strike, 0). Put intrinsic value is max(strike − underlying, 0). A simple long option’s expiry profit subtracts the premium paid and costs. Before expiry, pricing depends on more than intrinsic value.', ['In the money: positive intrinsic value.','At the money: underlying near the strike; the exact classification convention may vary.','Out of the money: no intrinsic value, yet the option can still have a premium before expiry.'], 'A hypothetical call with strike 1,000 bought for 30 has intrinsic value 20 when expiry settlement is 1,020. The expiry outcome is a 10-unit loss before costs, despite being in the money.'),
section('Time value, implied volatility and breakeven','The premium above intrinsic value is often called time or extrinsic value. Time remaining, expected variability, rates and other contract factors influence pricing. A rise in the underlying does not guarantee a call buyer’s profit if other factors move unfavorably.', ['Simple long-call expiry breakeven: strike + premium, before costs.','Simple long-put expiry breakeven: strike − premium, before costs.','Expiry breakeven is not a universal price at which a pre-expiry position becomes profitable.','Implied volatility is an input inferred from option prices through a model; it is not a direction forecast.']),
section('Indian index and stock contracts need separate checks','Do not assume that an index option and an individual-stock option settle the same way. Check the current NSE contract specifications and your broker’s margin and settlement policies. Lot size, expiry schedules and eligible contracts can change.', ['Know the quantity multiplier before converting points into rupees.','Delivery obligations, exercise treatment and broker cutoffs can change practical risk.','Uncovered calls have theoretically unlimited loss; uncovered puts can have substantial downside. A seller’s margin is not a loss cap.'])],
'For a fictional call with strike 1,000 and premium 30, compute expiry outcomes at 980, 1,000, 1,020 and 1,080. Explain the difference between intrinsic value and profit.',
{q:'A call expires 20 points in the money after costing 30. Its outcome before costs is:',options:['+20','−10','+50'],answer:1,why:'Intrinsic value 20 minus premium 30 equals a 10-point loss per unit.'},
[['Option moneyness','https://zerodha.com/varsity/chapter/moneyness-of-an-option-contract/'],['NSE derivatives products','https://www.nseindia.com/products-services/equity-derivatives-contract-specifications']]);
lesson('option-chain-and-greeks','Nifty option chains and the Greeks','Options','Read a chain as contract information, not a prediction machine.','chain',[
section('Start with the same underlying and expiry','An option chain groups calls and puts by strike for a selected expiry. Read the underlying reference, timestamp, bid and ask, quantities, last-traded price and settlement conventions. Stale last trades can make an apparently cheap option impossible to buy at that price.', ['Strike identifies the exercise reference; it is not the premium.','The bid–ask spread and depth affect executable prices.','Compare like-for-like expiries; different maturities contain different time and event exposure.','Our Nifty-style lab uses invented numbers, not a live feed or exchange trading signal.']),
section('Open interest needs both sides of a contract','Open interest counts outstanding contracts; volume counts traded activity during an interval. Every open contract has a long and a short side. An increase in open interest does not, by itself, prove bullish or bearish intent.', ['Opening and closing transactions can affect open interest differently.','High open interest is not a guaranteed support or resistance wall.','PCR, max pain and changes in open interest are contextual statistics, not reliable standalone forecasts.','Check the source’s units: contracts, lots and underlying quantity are not interchangeable.']),
section('Four useful sensitivities','Delta estimates sensitivity to a small underlying-price change. Gamma describes how delta changes. Theta estimates time-passage sensitivity; vega estimates sensitivity to implied volatility. These values come from models and move as conditions change.', ['Delta is not a fixed exposure or a guaranteed probability.','Near-expiry gamma can make exposure change quickly.','Bought options generally lose time value as time passes, other factors equal.','An implied-volatility fall can offset a favorable underlying move.']),
section('Volatility surfaces and events','Different strikes can show different implied volatilities, called skew or smile. Different expiries form a term structure. An event can raise option premiums beforehand and reduce them afterwards even when the underlying moves. Low premium does not necessarily mean low risk or good value.', ['Assess liquidity and missing or extreme IV readings before interpreting them.','Do not compare a distant out-of-the-money option only by its low rupee price.','Model estimates simplify a world with jumps, changing liquidity and execution costs.'])],
'In the option-chain lab, select a strike below and above the reference index. Explain which call or put has intrinsic value, then explain why open interest cannot reveal one certain direction.',
{q:'Rising open interest alone proves:',options:['New bullish positions only','New bearish positions only','Neither; every contract has a long and a short'],answer:2,why:'Open interest counts outstanding contracts. Directional interpretation requires more context and remains uncertain.'},
[['Open interest and volume','https://zerodha.com/varsity/chapter/open-interest/'],['Option Greeks explained','https://support.zerodha.com/category/account-opening/glossary/futures-and-options/articles/what-are-option-greeks']]);
lesson('options-strategies','Options structures and payoff logic','Options','Compare directional, volatility and hedging structures—plus their failure modes.','payoff',[
section('Start with legs and cash flows','A strategy name hides a set of contracts. Write every leg: buy or sell, call or put, strike, expiry, quantity and premium. Then sum each leg’s result at the same assumed settlement price. The expiry picture does not describe every pre-expiry mark-to-market path.', ['Debit: premium paid to establish the structure.','Credit: premium received; this is not immediately earned profit.','Equal quantities and same expiry are crucial assumptions in a simple vertical-spread diagram.']),
section('Directional vertical spreads','A bull call spread buys a lower-strike call and sells a higher-strike call. In a simplified same-expiry model its maximum loss is the net debit and maximum gain is strike width minus debit. A bear put spread uses a higher-strike long put and a lower-strike short put. Credit spreads express the complementary payoff through short and protective long legs.', ['A bull put spread combines a short higher-strike put and a long lower-strike put.','A bear call spread combines a short lower-strike call and a long higher-strike call.','The advertised risk limit assumes the complete structure stays in place and settlement assumptions hold. Legging in or out can expose different risk.']),
section('Movement and range structures','A long straddle buys a call and a put at the same strike; enough movement is needed to overcome the combined premium at expiry. A long strangle uses separate out-of-the-money strikes. An iron condor combines a put credit spread below and a call credit spread above. It caps both favorable and unfavorable expiry outcomes in the simplified model.', ['A short straddle or strangle without protective wings can create very large or unlimited losses.','Butterflies concentrate a payoff around a region; small-looking debit does not imply a high chance of profit.','Calendar and diagonal spreads span expiries, so a single one-expiry intrinsic-value chart is insufficient.','Ratio spreads can leave excess uncovered options. Check the remaining tail exposure.']),
section('Hedging is a trade-off, not free protection','A protective put adds a purchased put to an underlying holding; insurance costs premium. A covered call caps upside while retaining substantial underlying downside. A collar combines a holding, a protective put and a short call, exchanging some upside for protection under stated terms.', ['Payoff labs here use hypothetical, European-style cash-settled, one-unit examples at expiry before costs.','Real outcomes depend on quantity, liquidity, exercise style, settlement, margin and broker handling.','No structure shown is a personal recommendation or an instruction to place a trade.'])],
'Compare a long call with a bull call spread in the payoff lab. Identify the price region where giving up unlimited upside reduces the premium paid. Then inspect both losing cases.',
{q:'For a 100-point-wide debit spread costing 30, the simplified maximum expiry gain is:',options:['30','70','Unlimited'],answer:1,why:'Strike width 100 minus debit 30 equals 70 per unit, before costs and contract complications.'},
[['OIC bull call spread','https://www.optionseducation.org/strategies/all-strategies/bull-call-spread-debit-call-spread'],['OIC iron condor','https://www.optionseducation.org/strategies/all-strategies/short-condor']]);
lesson('stocks-and-swing','Stocks, company context and swing study','Stocks','Connect a business, a sector and a chart without ignoring overnight risk.','market',[
section('A stock is a business claim','A share’s price reflects changing expectations about cash flows, growth, financing and risk. A good company is not automatically a good investment at every price. A price chart alone does not provide a full picture of debt, governance or dilution.', ['Read exchange filings and company results, not just summaries on social media.','Distinguish revenue, profit and operating cash flow.','Valuation ratios need comparable businesses and context; a low ratio can reflect genuine problems.']),
section('Context can move a group together','Sector demand, regulation, input costs and interest rates can affect related companies. Index weights mean large constituents can influence an index more than small constituents. Breadth asks how widely a move is shared.', ['Relative strength compares one series with another; it is not the same calculation as RSI.','A stock outperforming an index can still be falling in absolute terms.','Correlation changes through time, especially during stress.']),
section('Overnight holding creates event exposure','Swing and positional approaches face earnings surprises, corporate actions, announcements and global events while the domestic market is closed. The next opening price may jump past planned exits. A tight plotted stop does not eliminate gap risk.', ['Understand dividends, splits, rights issues and adjusted chart data.','Check scheduled company events before interpreting historical gaps.','Liquidity can deteriorate when everyone wants to exit together.']),
section('Build a research watchlist','Write the reason each symbol is included, the source date and the evidence that would contradict the idea. Separate business research from a technical timing experiment. Use paper observation first and review rejected ideas as well as attractive charts.', ['Record market context, company event, chart condition and invalidation.','Avoid survivorship bias: today’s successful companies are not the entire historical opportunity set.','Keep your research process separate from rumors or personalized recommendations.'])],
'Compare a fictional stock falling 3% with its sector falling 8%. Explain relative outperformance, absolute loss and why neither alone proves future returns.',
{q:'Relative outperformance means the stock must be rising:',options:['True','False'],answer:1,why:'It can decline less than the benchmark and still outperform on a relative basis.'},
[['NSE investor education','https://www.nseindia.com/static/invest/investors-home'],['SEBI investor caution','https://investor.sebi.gov.in/cautiontoinvestor.html']]);
lesson('crypto-markets','Crypto, custody and leveraged contracts','Crypto','Learn the structures without confusing availability with safety or permission.','crypto',[
section('Asset and venue are separate risks','Bitcoin and Ether are examples of crypto assets with different network designs and uses. Owning an asset through a venue adds platform and custody risk beyond the asset’s price. Crypto trading can run around the clock, but that does not mean liquidity or withdrawals are always available.', ['Spot ownership differs from a futures or perpetual contract.','A venue’s displayed balance is not proof that reserves, withdrawal access or legal protections are adequate.','Stablecoin is a category label, not a guarantee of a stable redemption value.']),
section('Custody determines who controls access','A private key controls the ability to authorize transactions for an address. With custodial services, access depends on the provider and its controls. Self-custody moves responsibility for keys, backups and transaction accuracy to the holder; mistakes can be irreversible.', ['Never share a seed phrase or private key.','Check the network and address carefully; similarly named tokens can be unrelated.','Beware impersonation, phishing, fake support and promises of guaranteed yield.']),
section('Perpetuals, funding and liquidation','Perpetual contracts generally have no scheduled expiry and use mechanisms such as funding payments to relate their prices to a reference. Funding conventions, mark prices, margin modes and liquidation rules differ by platform. Leverage magnifies sensitivity to relatively small price changes.', ['Initial margin is collateral, not a guaranteed maximum loss.','A liquidation price can change as collateral, fees, funding and position size change.','Cross margin can expose collateral beyond a single position; isolated configurations also have specific rules and risks.','Exchange failure, interruptions and rapid gaps are not captured by a tidy chart backtest.']),
section('Check local rules before considering participation','Product availability online is not proof that offering, accessing or funding it is lawful or appropriate where you live. Tax, reporting, exchange-control and platform rules differ and change. This library does not recommend an exchange, token or leveraged product.', ['Use official local sources and qualified advice for your circumstances.','An education example is not an invitation to bypass restrictions.','Keep the first exercises hypothetical: structure, cash flows, custody failure and adverse scenarios.'])],
'Compare holding a fictional asset outright with a 10× leveraged contract. List price risk, custody risk, liquidation risk and platform risk separately.',
{q:'Does a displayed exchange balance eliminate custody risk?',options:['Yes','No'],answer:1,why:'A balance on a screen does not guarantee withdrawal, solvency or control of the asset.'},
[['Investor.gov crypto education','https://www.investor.gov/additional-resources/spotlight/crypto-assets'],['RBI foreign-exchange FAQ','https://www.rbi.org.in/scripts/FS_FAQs.aspx?Id=146']]);
lesson('currency-markets','Currencies and the India rulebook','Currencies','Pairs, quotation, rate differentials, macro drivers and authorized routes.','global',[
section('Read the quotation first','A currency pair expresses one currency in units of another. In USD/INR, the quote describes rupees per US dollar. If the quote rises, a dollar buys more rupees: the rupee has weakened against the dollar in that quotation. Inverting the pair reverses the numerical direction.', ['The first currency is the base and the second is the quote.','Pip and tick conventions depend on the instrument and venue.','A cash conversion, an exchange-traded derivative and an offshore leveraged CFD are different products.']),
section('Currencies reflect relative conditions','Interest-rate expectations, inflation, trade flows, capital flows and risk sentiment can all influence exchange rates. These factors interact and can already be reflected in price. A higher local interest rate does not mechanically guarantee a stronger currency.', ['Expected policy changes can matter more than the announcement itself.','Commodity prices can affect importing and exporting economies differently.','Central-bank communication and intervention are sources of uncertainty, not predictable trading rules.']),
section('Indian residents must use permitted routes','RBI guidance states that residents may undertake forex transactions only with authorized persons for permitted purposes. Electronic forex transactions must follow applicable rules for authorized electronic trading platforms or recognized exchanges. The existence of a foreign website is not authorization to use it.', ['Check RBI authorization, the permitted purpose and your eligibility—not merely an advertisement or app-store listing.','Do not assume offshore forex or CFD funding is allowed.','Recognized-exchange products also have eligibility, documentation and contract requirements.','Consult current RBI and exchange guidance before any real transaction.']),
section('Study contracts without importing the wrong assumptions','Currency futures and options have their own quotation, quantity, expiry and settlement rules. A chart labeled EUR/USD elsewhere is not automatically the same product available through an Indian broker. Holidays and international sessions can alter liquidity.', ['Verify exact contract specifications and broker support.','Include spread, costs and rollover or funding where applicable.','This chapter explains concepts and does not recommend a pair or venue.'])],
'If USD/INR changes from a fictional 80 to 82, explain which currency weakened in this quote. List the authorization checks an Indian resident must make.',
{q:'A foreign trading app is downloadable in India. Does that establish RBI authorization?',options:['Yes','No'],answer:1,why:'Availability is not authorization. RBI permissions, purpose and platform status must be checked separately.'},
[['RBI forex permissions and platforms','https://www.rbi.org.in/scripts/FS_FAQs.aspx?Id=146'],['NSE currency contract specifications','https://www.nseindia.com/static/products-services/currency-derivatives-contract-specification-inr']]);
lesson('global-macro','How the world reaches an Indian chart','Global markets','Rates, inflation, currencies, oil, global sessions and the expectation gap.','global',[
section('Follow a transmission channel, not a headline','A global event can affect Indian markets through earnings expectations, financing costs, currency movements, commodity prices or investors’ willingness to take risk. Different sectors may respond differently. The same headline can produce a different response in a different economic setting.', ['Higher oil can pressure some importers and benefit some producers; other variables can offset the effect.','Currency changes affect import costs and foreign revenues differently across companies.','Changes in global risk appetite can alter capital flows, without dictating every stock’s next move.']),
section('Expectations matter as much as the number','Markets react to information relative to what was already expected and positioned for. A strong data release may support earnings expectations yet raise concerns about tighter monetary policy. The net response is conditional, not a reliable one-line rule.', ['Compare release, prior value, revisions and a clearly sourced expectation.','Distinguish policy rates from market bond yields; long-term yields include expectations and risk compensation.','Do not infer causation from two charts moving together once.']),
section('Use an event map','Economic releases, central-bank decisions, earnings and geopolitical developments can change volatility. A calendar helps identify uncertainty; it does not predict the result. Time zones and daylight-saving changes matter when comparing overseas sessions with India.', ['India: RBI communications, inflation, activity indicators, fiscal policy and corporate results.','Global: major central-bank decisions, inflation and labor-market releases, oil developments and geopolitical risk.','Read official releases where possible and timestamp your observation.']),
section('Write two or more scenarios','A useful pre-session note separates known facts, uncertain outcomes and what would change the interpretation. Combine global context with domestic breadth, sector behavior, liquidity and actual price response. Never treat a macro opinion as permission to ignore risk.', ['Scenario A: conditions continue; what observable evidence would fit?','Scenario B: conditions disappoint or reverse; what would invalidate the first view?','No-trade condition: uncertainty or execution risk makes a paper observation more appropriate.'])],
'Build a fictional event map for an RBI announcement and a US inflation release. Write two plausible but different market responses and the assumptions behind each.',
{q:'Why can a strong economic release be followed by falling shares?',options:['Markets always behave irrationally','It may change rate expectations or differ from positioning','Strong releases never cause declines'],answer:1,why:'Prices respond to multiple channels and prior expectations, not just whether a headline sounds positive.'},
[['Federal Reserve: how monetary policy works','https://www.federalreserve.gov/monetarypolicy/monetary-policy-what-are-its-goals-how-does-it-work.htm'],['RBI official website','https://www.rbi.org.in/']]);
lesson('gift-nifty','GIFT Nifty: a cue, not a crystal ball','Global markets','What GIFT Nifty represents and why it cannot guarantee the Indian open.','gift',[
section('Know the instrument','GIFT Nifty refers to Nifty-related derivatives traded at NSE International Exchange in GIFT City. The flagship Nifty futures contract is US-dollar-denominated. It is a futures market referencing the Nifty 50, not the cash Nifty index itself and not the same instrument as a domestic ETF.', ['NSE IX operates in the international financial-services environment under its applicable framework.','The SGX Nifty transition to GIFT Nifty took place in 2023; old screenshots may use the earlier name.','Check current NSE IX specifications, trading hours, holidays and access requirements rather than relying on a fixed timetable from an old post.']),
section('Why people look at it before India opens','Trading outside the domestic cash session can reflect overseas news and changing risk sentiment while the Indian cash market is closed. That makes it a useful observation for context. Different timestamps, expiry contracts and liquidity mean comparisons need care.', ['Identify the contract month, timestamp and quote source.','Compare like-for-like futures observations, not an overnight futures quote with an unrelated spot timestamp.','A thin or stale quote can be misleading.']),
section('Understand the basis','Futures and spot need not trade at identical levels. Financing, expected dividends, time to expiry, liquidity and other market conditions influence the difference. A positive futures–spot gap is not automatically a prediction of an equally large cash-market gap.', ['Basis means futures price minus spot reference at a comparable time.','Different expiry contracts can have different basis values.','An overnight change can be partly or fully reversed before the cash open.'], 'Fictional cash reference: 24,000. GIFT futures quote: 24,080. The 80-point difference is not a promise that Nifty will open at 24,080. Timing, carry, expiry and fresh information all matter.'),
section('A careful morning checklist','Use GIFT Nifty alongside overnight US and Asian conditions, oil, currencies, scheduled domestic events and fresh company information. After the Indian market opens, observe the actual cash-market response rather than forcing it to match an earlier cue.', ['Write facts and timestamps before drawing a scenario.','Mark uncertainty explicitly; there is no guaranteed directional signal.','This is education about context, not a live GIFT quote, access recommendation or trading instruction.'])],
'Use the illustrated basis example and explain three reasons the cash open can differ from a GIFT futures quote. Check the current official hours yourself before using any timetable.',
{q:'GIFT futures are 80 points above an earlier cash reference. The next cash open is guaranteed to be:',options:['Exactly 80 points higher','Higher, but not exactly 80','Not guaranteed by that observation'],answer:2,why:'Different timestamps, futures basis and new information prevent a guaranteed one-to-one opening prediction.'},
[['NSE: GIFT Nifty identity and structure','https://www.nseindia.com/static/resources/nse-international-exchange-unveils-a-new-identity-for-gift-nifty'],['NSE IX official exchange','https://www.nseix.com/']]);
lesson('testing-and-systems','From an idea to a testable process','Risk & process','Backtesting, journals, scanners, coding concepts and why a beautiful equity curve can mislead.','testing',[
section('Define a rule a second person can reproduce','A research idea needs explicit inputs, conditions, timing and exits. “Buy a strong breakout” is ambiguous. A testable version specifies the lookback, boundary, confirmation, signal time and fill assumption. That precision still does not establish a profitable edge.', ['Record the universe and dates before evaluating results.','Specify transaction costs, spread, slippage and whether shorting or leverage is permitted.','Avoid changing the rule every time a losing example appears.']),
section('Separate development from evaluation','Use one sample for developing an idea and another untouched sample for evaluation. Walk-forward research repeats the process through successive periods. Trying many settings and reporting only the best is a form of selection bias.', ['Look-ahead bias uses information not available at the decision time.','Survivorship bias leaves out failed or delisted securities.','Overfitting captures historical noise instead of a repeatable relationship.','Include multiple market conditions and report uncertainty; a small sample can look excellent by chance.']),
section('Learn what a backtester actually simulates','Pine Script strategies in TradingView model hypothetical orders and fills. Default assumptions, intrabar movement, gaps and transformed chart prices can change the result. An alert is not necessarily a completed order, and an automated connection introduces operational risk.', ['Begin with standard OHLC charts and inspect the simulator’s assumptions.','Check repainting and unfinished-bar behavior before comparing alerts with history.','Start coding with variables, conditions and plots; then add one explicit rule and realistic friction.','A screener finds candidates matching conditions; it does not verify their suitability or guarantee outcomes.']),
section('Report more than the total return','Win rate, average win, average loss, costs, drawdown, trade count, concentration and time under water describe different parts of a result. Profit factor divides gross winning amounts by gross losing amounts; no losses in a tiny sample does not establish an infinite-quality strategy.', ['Review outliers and the sequence of outcomes, not only the average.','Compare paper assumptions with observed execution constraints.','Keep a versioned plan and journal; write what would make you stop researching an idea.','No historical test proves future profitability.'])],
'Write a hypothetical breakout rule precise enough for someone else to test. Identify the earliest time each input becomes known, then list three ways the test could accidentally use future information.',
{q:'Testing 500 settings and reporting only the best mainly raises which concern?',options:['Overfitting and selection bias','Guaranteed consistency','Lower execution costs'],answer:0,why:'Selecting the best historical result among many trials can fit noise and overstate future performance.'},
[['TradingView strategy simulation','https://www.tradingview.com/pine-script-docs/concepts/strategies/'],['TradingView repainting','https://www.tradingview.com/pine-script-docs/concepts/repainting/']]);
lesson('build-your-trading-plan','Build a written learning & trading plan','Risk & process','Bring context, rules, execution and review together without confusing a plan with a profit promise.','testing',[
section('Separate a learning goal from a money goal','A learning goal is observable: explain a contract, calculate a payoff or identify an invalidation rule. A daily income target does not make the market offer a suitable opportunity. Begin with what you need to understand and how you will check that understanding.', ['Choose one instrument family and one observation timeframe for a study exercise.','List the missing knowledge before attempting a strategy: contract, liquidity, costs and settlement.','Keep essential spending and personal financial commitments outside a speculative experiment.']),
section('Write a one-page decision framework','A repeatable framework records the market context, the condition being studied, the assumptions behind it and the evidence that would contradict it. Include a no-trade condition. A plan is useful because it exposes decisions to review, not because it makes outcomes certain.', ['Context: date, data source, event calendar, trend or range and nearby reference zones.','Hypothesis: precise condition, observation time and alternative explanation.','Risk: fictional entry, invalidation, quantity calculation, friction and adverse-gap scenario.','Execution: order assumptions, partial fills, rejects and what happens if the platform disconnects.']),
section('Run a paper exercise from start to finish','Record the plan before revealing the next prices. Document whether the assumed entry could plausibly fill, including spread and available information at that time. If a rule changes during the exercise, preserve the original version and explain the change rather than rewriting history.', ['Collect both fitting and non-fitting examples, not only winners.','Separate process adherence from the financial result.','Use a fixed evaluation sample and do not turn a few paper wins into a claim of live readiness.'], 'A fictional plan may say: observe whether a defined range is broken on a completed bar; do nothing during a scheduled release; record a failed break as well as a continuing move. This is a study protocol, not a recommended entry rule.'),
section('End with a review, not a verdict on yourself','Review decisions, data quality, execution assumptions and uncertainty. A losing example can teach something useful; a profitable example can still rely on a bad assumption. Decide what to study next and what evidence would make you abandon the idea.', ['Use the local journal to record observation, evidence, alternative scenario and review.','Check your understanding with the lesson questions and work through losing payoff examples.','Read current official rules before any real transaction; seek qualified help for personal financial decisions.','The goal of this library is understanding. It does not certify competence or establish that trading is suitable for you.'])],
'Write your one-page paper-study plan. Include at least one no-trade condition, one adverse execution scenario and an explicit reason you might reject the idea after testing.',
{q:'A profitable paper trade proves the plan is ready for live trading:',options:['Yes','No'],answer:1,why:'One result does not establish robust evidence, realistic execution, suitability or future profitability.'},
[['SEBI investor caution','https://investor.sebi.gov.in/cautiontoinvestor.html'],['TradingView backtesting assumptions','https://www.tradingview.com/pine-script-docs/concepts/strategies/']]);
module.exports={lessons,lesson,section};
