'use strict';
const assert=require('node:assert/strict'),{webcrypto}=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const offline=require('../trading/offline.js'),auth=require('../trading/source/auth.cjs');
const example='Public-test-password-2026',bundle={schema:1,sourceRole:'learner',savedAt:'2026-10-01T08:00:00.000Z',permit:'test-offline-permit',pages:require('../trading/source/app-pages.json')};
let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name);}
async function main(){
  let record;
  await test('Every learning section encrypts and decrypts without losing graphics or study tools',async()=>{record=await offline.seal(bundle,example,webcrypto);assert.equal(record.pages,23);assert(record.bytes>100000);assert.equal(record.salt.length,16);assert.equal(record.iv.length,12);assert.equal(offline.ITERATIONS,600000);assert.deepEqual(await offline.unseal(record,example,webcrypto),bundle);assert(!Object.hasOwn(record,'password'));assert(!Object.hasOwn(record,'pagesHTML'));assert(!Buffer.from(record.cipher).includes(Buffer.from('GIFT Nifty')));});
  await test('Wrong passwords and tampered downloads are rejected',async()=>{await assert.rejects(()=>offline.unseal(record,'Wrong-password-2026',webcrypto),/cannot unlock/);const damaged={...record,cipher:record.cipher.slice(0)},bytes=new Uint8Array(damaged.cipher);bytes[20]^=255;await assert.rejects(()=>offline.unseal(damaged,example,webcrypto),/cannot unlock/);await assert.rejects(()=>offline.unseal(null,example,webcrypto),/No complete/);});
  await test('Encryption uses fresh randomness and rejects invalid payloads',async()=>{const again=await offline.seal(bundle,example,webcrypto);assert.notDeepEqual(again.salt,record.salt);assert.notDeepEqual(again.iv,record.iv);assert.notDeepEqual(again.cipher,record.cipher);await assert.rejects(()=>offline.seal({},example,webcrypto),/incomplete/);await assert.rejects(()=>offline.seal(bundle,'short',webcrypto),/15–128/);});
  await test('Offline permits cannot grant online sessions or owner powers',()=>{const s={signingKey:auth.random(),ownerVersion:1,learnerVersion:1},permit=auth.signOfflinePermit(s,'learner');assert.equal(auth.readOfflinePermit(permit,s).role,'learner');assert.equal(auth.readSession(permit,s),null);assert.equal(auth.readOfflinePermit(permit+'x',s),null);s.learnerVersion++;assert.equal(auth.readOfflinePermit(permit,s),null);const owner=auth.signOfflinePermit(s,'owner');s.ownerVersion++;assert.equal(auth.readOfflinePermit(owner,s),null);});
  await test('Offline app files are verified before a download is reported ready',async()=>{const handlers={},messages=[],waits=[];const ctx={URL,self:{location:{origin:'https://local'},addEventListener:(n,f)=>handlers[n]=f},caches:{open:async()=>({match:async()=>({ok:true})})}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../trading/sw.js'),'utf8'),ctx);handlers.message({data:{type:'VERIFY_OFFLINE_SHELL'},ports:[{postMessage:data=>messages.push(data)}],waitUntil:p=>waits.push(p)});await Promise.all(waits);assert.equal(messages[0].ready,true);ctx.caches.open=async()=>({match:async()=>undefined});handlers.message({data:{type:'VERIFY_OFFLINE_SHELL'},ports:[{postMessage:data=>messages.push(data)}],waitUntil:p=>waits.push(p)});await Promise.all(waits);assert.equal(messages[1].ready,false);});
  await test('Homepage and app clearly expose install, download and offline unlock controls',()=>{const home=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),app=fs.readFileSync(path.join(__dirname,'../trading/app.html'),'utf8'),install=fs.readFileSync(path.join(__dirname,'../trading/install.html'),'utf8');assert.match(home,/Install Trade Zuko/);assert.match(home,/href="\/trading\/install\?install=1" data-install-trigger/);assert.match(app,/data-offline-save/);assert.match(app,/data-offline-login/);assert.match(app,/name="consent" required/);assert.match(install,/YouTube\/Instagram videos/);assert.match(install,/Download all lessons for offline use/);assert.match(app,/src="\/trading\/offline.js\?v=1"/);});
  console.log('\n'+count+' offline-learning checks passed.');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
