'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),math=require(path.join(root,'trading/math.js')),auth=require(path.join(root,'trading/source/auth.cjs'));
let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name);}
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(d=>d.isDirectory()?walk(path.join(dir,d.name)):[path.join(dir,d.name)]);
const docs=['index','youtube','instagram','trading',...walk(path.join(root,'trading')).filter(f=>f.endsWith('.html')).map(f=>path.relative(root,f).replace(/\\/g,'/').slice(0,-5))];
const fileFor=url=>{let p=url.pathname==='/'?'/index.html':url.pathname;if(!path.extname(p))p+='.html';return path.join(root,p.slice(1));};
async function main(){
for(const name of docs)await test(name+': metadata, unique IDs, valid local links and assets',()=>{const file=path.join(root,name+'.html'),html=fs.readFileSync(file,'utf8');assert.equal([...html.matchAll(/<h1\b/g)].length,1);assert.match(html,/<title>[^<]*Aman Singh/);assert.match(html,/<link rel="canonical"/);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,'duplicate ID');for(const m of html.matchAll(/(?:href|src)="([^"\s]+)"/g)){if(/^(https?:|mailto:|tel:|data:)/.test(m[1]))continue;const u=new URL(m[1],'https://local/'+(name==='index'?'':name));const target=fileFor(u);assert(fs.existsSync(target),name+' → '+m[1]);if(u.hash&&path.extname(target)==='.html'){const targetHtml=fs.readFileSync(target,'utf8');assert(targetHtml.includes('id="'+u.hash.slice(1)+'"'),name+' → missing '+m[1]);}}for(const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g))JSON.parse(m[1]);assert(!/href="[^"]*Aman-Singh-Resume/.test(html));if(name!=='index')assert(!html.includes('href="https://github.com/Amansingh4848"'));});
await test('16 complete lessons / 32 original patterns / 62 tier-specific modules',()=>{const {lessons}=require(path.join(root,'trading/source/lessons.cjs')),patterns=require(path.join(root,'trading/source/patterns.cjs')),courses=require(path.join(root,'trading/source/courses.json'));assert.equal(lessons.length,16);assert.equal(patterns.length,32);assert.deepEqual(courses.map(c=>c.modules.length),[24,18,20]);assert.deepEqual(courses.map(c=>c.duration),['4–5 weeks','6–7 weeks','8–10 weeks']);for(const l of lessons){assert.equal(l.sections.length,4);assert(l.exercise.length>50);assert(l.quiz.answer>=0&&l.quiz.answer<l.quiz.options.length);assert(l.sources.length);}});
await test('All 11 payoff structures respect model maximum loss and expiry breakevens',()=>{assert.equal(math.strategies.length,11);for(const s of math.strategies){for(let x=0;x<=5000;x+=5)assert(s.fn(x)>=-s.loss-1e-9,s.id+' loss bound');for(const v of s.breakeven.split(' / '))assert(Math.abs(s.fn(Number(v.replaceAll(',',''))))<1e-9,s.id+' breakeven');}assert.equal(math.strategies.find(s=>s.id==='condor').fn(1000),30);assert.equal(math.strategies.find(s=>s.id==='condor').fn(600),-70);assert.equal(math.strategies.find(s=>s.id==='covered-call').fn(0),-980);});
await test('Risk and expectancy validate inputs, cap cash and include friction',()=>{assert.deepEqual(math.size({capital:100000,budget:1000,entry:100,stop:98,friction:.5}),{risk:2.5,quantity:400,planned:1000,notional:40000});assert.equal(math.expectancy(40,200,100,25),-5);assert.equal(math.size({capital:50,budget:1,entry:100,stop:99,friction:0}).quantity,0);assert.throws(()=>math.size({capital:1000,budget:10,entry:100,stop:100,friction:0}));assert.throws(()=>math.expectancy(101,1,1,0));});
await test('Manifest uses trading-only scope, genuine PNG icons and no fake store links',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'trading/manifest.webmanifest')));assert.equal(m.name,'Trade Zuko');assert.equal(m.scope,'/trading/');assert(m.start_url.startsWith(m.scope));for(const icon of m.icons){const b=fs.readFileSync(path.join(root,icon.src.slice(1)));assert.equal(b.readUInt32BE(0),0x89504e47);assert.equal(b.readUInt32BE(16),Number(icon.sizes.split('x')[0]));}const html=fs.readFileSync(path.join(root,'trading/app.html'),'utf8');assert(!html.includes('play.google.com'));assert(!html.includes('apps.apple.com'));assert.match(html,/noindex, nofollow/);});
await test('Service worker excludes protected/API responses and caches only shell assets',async()=>{const handlers={},requests=[];const ctx={self:{location:{origin:'https://local'},addEventListener:(n,f)=>handlers[n]=f,clients:{claim:async()=>{}},skipWaiting:()=>{}},URL,fetch:async()=>({ok:true}),caches:{open:async()=>({addAll:async list=>{for(const u of list){assert(!u.startsWith('/api/'));assert(fs.existsSync(fileFor(new URL(u,'https://local'))));}}})} };vm.runInNewContext(fs.readFileSync(path.join(root,'trading/sw.js'),'utf8'),ctx);await handlers.install({waitUntil:p=>requests.push(p)});await Promise.all(requests);let intercepted=false;handlers.fetch({request:{method:'GET',url:'https://local/api/trade-access?action=content'},respondWith:()=>intercepted=true});assert.equal(intercepted,false);});
await test('App password hashes are salted and sessions reject tampering, expiry and rotation',async()=>{const a=await auth.hashPassword('Example-owner-secret-123'),b=await auth.hashPassword('Example-owner-secret-123');assert.notEqual(a.salt,b.salt);assert.notEqual(a.hash,b.hash);assert(await auth.verifyPassword('Example-owner-secret-123',a));assert(!await auth.verifyPassword('wrong',a));const s={ownerVersion:1,learnerVersion:1,signingKey:auth.random()},token=auth.signSession(s,'learner',100);assert(auth.readSession(token,s,101));assert.equal(auth.readSession(token+'x',s,101),null);assert.equal(auth.readSession(token,s,100+43200000),null);s.learnerVersion++;assert.equal(auth.readSession(token,s,101),null);});
await test('Durable attempt limits survive repeated calls and expire',()=>{const s={signingKey:'x'};for(let i=0;i<8;i++)auth.consumeAttempt(s,'test-ip',100);assert.throws(()=>auth.consumeAttempt(s,'test-ip',101),/Too many/);assert.doesNotThrow(()=>auth.consumeAttempt(s,'test-ip',900101));});
await test('Server login, role separation, origin/CSRF, rotation and recovery integration',async()=>{
let state={schema:1,owner:await auth.hashPassword('Owner-example-secret-123'),learner:await auth.hashPassword('Learner-example-secret-123'),recovery:await auth.hashPassword('Recovery-example-secret-123'),ownerVersion:1,learnerVersion:1,signingKey:auth.random(),attempts:{}},etag=1;
const adapter={get:async(_,options)=>{assert.equal(options.useCache,false);return {stream:new Response(JSON.stringify(state)).body,blob:{etag:String(etag)}};},put:async(_,text,options)=>{assert.equal(options.access,'private');if(options.ifMatch!==String(etag)){const e=Error();e.name='BlobPreconditionFailedError';throw e;}state=JSON.parse(text);etag++;return {};}};
const handler=require(path.join(root,'api/trade-access.js')).createHandler(async()=>adapter);let ip=0;
const request=async({method='GET',action='session',body={},cookie='',origin='https://aman-singh-resume.vercel.app',csrf='',page})=>{const headers={};let result;await handler({method,query:{action,page},body:{action,...body},headers:{'content-type':'application/json',origin,cookie,'x-zuko-csrf':csrf},socket:{remoteAddress:'test-'+ ++ip}},{setHeader:(k,v)=>headers[k]=v,end:text=>{result=JSON.parse(text);},set statusCode(v){headers.status=v;}});return {status:headers.status,body:result,headers,cookie:(headers['Set-Cookie']||'').split(';')[0]};};
assert.equal((await request({action:'content',page:'library'})).status,401);
assert.equal((await request({method:'POST',action:'login',origin:'https://evil.example',body:{role:'owner',password:'Owner-example-secret-123'}})).status,403);
assert.equal((await request({method:'POST',action:'login',body:{role:'owner',password:'Learner-example-secret-123'}})).status,401);
const learner=await request({method:'POST',action:'login',body:{role:'learner',password:'Learner-example-secret-123'}});assert.equal(learner.status,200);assert.match(learner.headers['Set-Cookie'],/HttpOnly; SameSite=Strict; Secure/);
assert.equal((await request({method:'POST',action:'change-owner',cookie:learner.cookie,csrf:learner.body.csrf,body:{newPassword:'Changed-owner-secret-123',ownerPassword:'Learner-example-secret-123'}})).status,403);
const owner=await request({method:'POST',action:'login',body:{role:'owner',password:'Owner-example-secret-123'}});assert.equal(owner.status,200);
assert.equal((await request({method:'POST',action:'change-learner',cookie:owner.cookie,csrf:'bad',body:{newPassword:'Changed-learner-secret-123',ownerPassword:'Owner-example-secret-123'}})).status,403);
assert.equal((await request({action:'content',page:'library',cookie:learner.cookie})).status,200);
assert.equal((await request({method:'POST',action:'change-learner',cookie:owner.cookie,csrf:owner.body.csrf,body:{newPassword:'Changed-learner-secret-123',ownerPassword:'Owner-example-secret-123'}})).status,200);
assert.equal((await request({cookie:learner.cookie})).status,401);
assert.equal((await request({method:'POST',action:'login',body:{role:'learner',password:'Learner-example-secret-123'}})).status,401);
assert.equal((await request({method:'POST',action:'login',body:{role:'learner',password:'Changed-learner-secret-123'}})).status,200);
assert.equal((await request({method:'POST',action:'change-owner',cookie:owner.cookie,csrf:owner.body.csrf,body:{newPassword:'Changed-owner-secret-123',ownerPassword:'Owner-example-secret-123'}})).status,200);
assert.equal((await request({cookie:owner.cookie})).status,401);
assert.equal((await request({method:'POST',action:'recover-owner',body:{recoveryKey:'Recovery-example-secret-123',newPassword:'Recovered-owner-secret-123'}})).status,200);
assert.equal((await request({method:'POST',action:'login',body:{role:'owner',password:'Recovered-owner-secret-123'}})).status,200);
});
console.log(`\n${count} Trade Zuko checks passed.`);
}
main().catch(e=>{console.error(e);process.exitCode=1;});
