(() => {
'use strict';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
let session=null,currentPage='library',navigation=0,installPrompt=null,checking=false;
const appMotion=$('[data-app-motion]');
function motionLabel(){const off=document.documentElement.dataset.motion==='off';appMotion.textContent=off?'Play motion':'Pause motion';appMotion.setAttribute('aria-label',off?'Play app animations':'Pause app animations');}
appMotion.addEventListener('click',()=>{$('.world-motion').click();motionLabel();});$('[data-app-theme]').addEventListener('click',()=>$('.theme-toggle').click());motionLabel();
const status=$('[data-app-status]'),content=$('[data-app-content]'),authPanel=$('[data-auth-panel]'),workspace=$('[data-app-workspace]'),ownerPanel=$('[data-owner-panel]');
async function api(action,data){const options={credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000)};let url='/api/trade-access?action='+encodeURIComponent(action);if(data){options.method='POST';options.headers={'Content-Type':'application/json','X-Zuko-CSRF':session?.csrf||''};options.body=JSON.stringify({action,...data});url='/api/trade-access';}const response=await fetch(url,options);const result=await response.json();if(!response.ok){const e=Error(result.error||'Request failed.');e.status=response.status;throw e;}return result;}
function lock(message='Please log in to Trade Zuko.'){session=null;navigation++;content.replaceChildren();workspace.hidden=true;ownerPanel.hidden=true;authPanel.hidden=false;$('[data-app-logout]').hidden=true;status.textContent=message;}
function authorize(s){session=s;authPanel.hidden=true;workspace.hidden=false;ownerPanel.hidden=s.role!=='owner';$('[data-app-logout]').hidden=false;status.textContent=s.role==='owner'?'Owner access — you control the learner password.':'Learner access — welcome to Trade Zuko.';}
function requestedPage(){const match=location.hash.match(/^#page=(.+)$/);if(!match)return 'library';try{return decodeURIComponent(match[1]);}catch{return 'library';}}
async function showPage(page,scroll=false){if(!session)return;const parts=page.split('#'),anchor=parts[1];page=parts[0];const id=++navigation;currentPage=page;content.setAttribute('aria-busy','true');try{const response=await fetch('/api/trade-access?action=content&page='+encodeURIComponent(page),{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok){const e=Error(data.error||'Unable to load lesson.');e.status=response.status;throw e;}if(id!==navigation||!session)return;content.innerHTML=data.html;window.TradeLearning.init(content);window.TradeLab?.init(content);all('[data-app-route]').forEach(b=>{if(b.dataset.appRoute===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(anchor){content.querySelector('#'+CSS.escape(anchor))?.scrollIntoView({block:'start'});}else if(scroll)workspace.scrollIntoView({behavior:document.documentElement.dataset.motion==='off'?'instant':'smooth',block:'start'});loadVideos();}catch(e){if(id!==navigation)return;if(e.status===401||e.status===403)lock('Access changed or expired. Log in again with the current password.');else{content.replaceChildren();const note=document.createElement('p');note.className='shell z-feedback';note.textContent=(e.status===404?'That lesson was not found.':'An internet connection is needed to verify access and load lessons.')+' Choose a page above to try again.';content.append(note);}}finally{if(id===navigation)content.removeAttribute('aria-busy');}}
function navigate(page){if(requestedPage()===page)showPage(page,true);else location.hash='page='+encodeURIComponent(page);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-app-route]');if(b){navigate(b.dataset.appRoute);return;}const local=e.target.closest('[data-app-content] a[href^="#"]');if(local){e.preventDefault();content.querySelector('#'+CSS.escape(local.getAttribute('href').slice(1)))?.scrollIntoView({block:'start'});return;}const a=e.target.closest('[data-app-content] a[href^="/trading/"]');if(a){const url=new URL(a.href);if(!url.pathname.endsWith('/app')){e.preventDefault();navigate(url.pathname.slice('/trading/'.length)+url.hash);}}});
addEventListener('hashchange',()=>{if(session&&location.hash.startsWith('#page='))showPage(requestedPage(),true);});
async function formRequest(form,task){const feedback=form.querySelector('.z-feedback'),button=form.querySelector('button[type=submit]');button.disabled=true;feedback.textContent='Checking securely…';feedback.dataset.error='false';try{await task(new FormData(form),feedback);form.reset();}catch(e){feedback.textContent=e.message||'Connection unavailable. Please try again.';feedback.dataset.error='true';}finally{button.disabled=false;}}
$('[data-login-form]').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;formRequest(form,async d=>{const s=await api('login',{role:d.get('role'),password:d.get('password')});authorize(s);await showPage(requestedPage(),true);});});
all('[data-password-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();formRequest(form,async(d,feedback)=>{if(d.get('newPassword')!==d.get('confirmPassword'))throw Error('The two new passwords do not match.');const result=await api('change-'+form.dataset.passwordForm,{ownerPassword:d.get('ownerPassword'),newPassword:d.get('newPassword')});if(result.loggedOut)lock(result.message);else feedback.textContent=result.message;});}));
$('[data-recovery-form]').addEventListener('submit',e=>{e.preventDefault();formRequest(e.currentTarget,async(d,feedback)=>{if(d.get('newPassword')!==d.get('confirmPassword'))throw Error('The two new passwords do not match.');const result=await api('recover-owner',{recoveryKey:d.get('recoveryKey'),newPassword:d.get('newPassword')});lock(result.message);feedback.textContent=result.message;});});
$('[data-app-logout]').addEventListener('click',async()=>{try{await api('logout',{});lock('You are logged out.');}catch{lock('This screen is locked. Reconnect and log out again to clear the server cookie, or close this private browsing session.');}});
async function check(initial=false){if(checking)return;checking=true;try{const s=await api('session');const hadSession=!!session;authorize(s);if(initial||!hadSession)await showPage(requestedPage());}catch(e){lock(e.status===401?'Enter your learner password, or choose owner access.':'Internet access is needed for secure login. Please reconnect and try again.');}finally{checking=false;}}
document.addEventListener('visibilitychange',()=>{if(document.hidden){content.hidden=true;}else{content.hidden=true;check().finally(()=>content.hidden=false);}});
addEventListener('pageshow',e=>{if(e.persisted)check(true);});addEventListener('offline',()=>lock('You are offline. Reconnect to verify access and continue learning.'));addEventListener('online',()=>check(true));setInterval(()=>{if(session&&!document.hidden)check();},60000);
async function loadVideos(){const area=content.querySelector('[data-app-videos]');if(!area)return;const grid=area.querySelector('[data-video-grid]'),notice=area.querySelector('[data-feed-status]');try{const response=await fetch('/api/youtube?channel=trading',{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error();const data=await response.json();if(!area.isConnected||!session)return;grid.replaceChildren();for(const v of data.videos){if(!/^https:\/\/www\.youtube\.com\/watch\?v=[A-Za-z0-9_-]{11}$/.test(v.url))continue;const a=document.createElement('a');a.className='live-video-card';a.href=v.url;a.target='_blank';a.rel='noopener noreferrer';const img=document.createElement('img');img.src=v.thumbnail;img.alt='';img.width=480;img.height=360;img.loading='lazy';const label=document.createElement('span');label.className='live-video-caption';label.textContent=v.title;a.append(img,label);grid.append(a);}notice.textContent=data.stale?'Showing recent cached channel updates. Open YouTube for the newest uploads.':'Latest public YouTube uploads. Open any thumbnail to watch.';const input=area.querySelector('[data-video-search]');input?.addEventListener('input',()=>{let n=0;[...grid.children].forEach(a=>{a.hidden=!a.textContent.toLowerCase().includes(input.value.toLowerCase());if(!a.hidden)n++;});const count=area.querySelector('[data-result-count]');if(count)count.textContent=n+' videos';});const count=area.querySelector('[data-result-count]');if(count)count.textContent=grid.children.length+' videos';}catch{if(notice)notice.textContent='Live channel updates are unavailable. Use the YouTube link or the selected videos below.';}}
const install=$('[data-install-app]'),installStatus=$('[data-install-status]');
function installed(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
if(installed()){install.hidden=true;installStatus.textContent='Trade Zuko is open in app mode.';}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;install.textContent='Install Trade Zuko';});
install.addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();const choice=await installPrompt.userChoice;installStatus.textContent=choice.outcome==='accepted'?'Installation accepted. Look for Trade Zuko on your device.':'You can install later from your browser menu.';installPrompt=null;install.textContent='Show installation options';}else{installStatus.textContent='Android: Chrome menu → Install app / Add to Home screen. iPhone: Safari Share → Add to Home Screen. Full steps are below.';$('.z-install-steps').scrollIntoView({behavior:'smooth'});}});
addEventListener('appinstalled',()=>{install.hidden=true;installStatus.textContent='Trade Zuko was installed. Open it from your device’s app icon.';});
if('serviceWorker'in navigator){navigator.serviceWorker.register('/trading/sw.js',{scope:'/trading/'}).then(reg=>{const update=$('[data-app-update]');const waiting=()=>{if(reg.waiting)update.hidden=false;};waiting();reg.addEventListener('updatefound',()=>{reg.installing?.addEventListener('statechange',waiting);});update.addEventListener('click',()=>{reg.waiting?.postMessage({type:'ACTIVATE_UPDATE'});});let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!refreshing&&navigator.serviceWorker.controller){refreshing=true;location.reload();}});}).catch(()=>{installStatus.textContent='Offline app shell could not be prepared. You can still use the app online; try reopening this page in your phone browser.';});}
check(true);
})();
