(() => {
'use strict';
const $=(s,root=document)=>root.querySelector(s),all=(s,root=document)=>[...root.querySelectorAll(s)];
const num=n=>Number(n).toLocaleString('en-IN',{maximumFractionDigits:2});
const read=key=>{try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}};
function save(key,data){try{localStorage.setItem(key,JSON.stringify(data));return true;}catch{return false;}}
const progressKey='trade-zuko-progress-v1',journalKey='trade-zuko-journal-v1';
let visualObserver;
function syncProgress(root=document){const saved=read(progressKey),progress=Array.isArray(saved)?saved.filter(v=>typeof v==='string'):[];all('[data-study-progress]',root).forEach(el=>el.textContent=progress.length+' / 16 lessons marked read');all('[data-progress-for]',root).forEach(el=>el.textContent=progress.includes(el.dataset.progressFor)?'Read ✓':'Open lesson');all('[data-mark-read]',root).forEach(el=>el.textContent=progress.includes(el.dataset.markRead)?'Lesson marked read ✓':'Mark this lesson read ✓');}
function init(root=document){
syncProgress(root);
const input=$('[data-filter-input]',root),category=$('[data-filter-category]',root),grid=$('[data-filter-grid]',root);
if(input&&grid&&!input.dataset.ready){input.dataset.ready='true';const filter=()=>{const q=input.value.toLowerCase().trim(),c=category?.value||'';let count=0;[...grid.children].forEach(card=>{card.hidden=!(card.dataset.search||'').includes(q)||(!!c&&card.dataset.category!==c);if(!card.hidden)count++;});const empty=$('[data-filter-empty]',root);if(empty)empty.hidden=count!==0;};input.addEventListener('input',filter);category?.addEventListener('change',filter);}
all('[data-mark-read]',root).forEach(button=>{if(button.dataset.ready)return;button.dataset.ready='true';button.addEventListener('click',()=>{const before=read(progressKey);const progress=Array.isArray(before)?before:[];if(!progress.includes(button.dataset.markRead))progress.push(button.dataset.markRead);const ok=save(progressKey,progress);syncProgress(root);const status=$('[data-progress-status]',button.parentElement);if(status)status.textContent=ok?'Saved on this browser.':'This browser could not save progress. Your lesson remains available.';});});
all('.z-quiz',root).forEach(form=>{if(form.dataset.ready)return;form.dataset.ready='true';form.addEventListener('submit',e=>{e.preventDefault();const selected=new FormData(form).get('answer');const good=String(selected)===form.dataset.answer,status=$('.z-feedback',form);status.textContent=(good?'Correct. ':'Review this one. ')+form.dataset.explanation;status.dataset.error=String(!good);});});
const risk=$('[data-risk-form]',root);if(risk&&!risk.dataset.ready){risk.dataset.ready='true';risk.addEventListener('submit',e=>{e.preventDefault();const out=$('[data-risk-result]',risk);try{const x=window.TradeMath.size(Object.fromEntries([...new FormData(risk)].map(([k,v])=>[k,Number(v)])));out.textContent=`Model quantity: ${num(x.quantity)} whole shares\nPlanned risk: ${num(x.planned)} · Position value: ${num(x.notional)}\nPlanned risk per share: ${num(x.risk)} (not a guaranteed loss cap)`;out.dataset.error='false';}catch(e){out.textContent=e.message;out.dataset.error='true';}});}
const exp=$('[data-expectancy-form]',root);if(exp&&!exp.dataset.ready){exp.dataset.ready='true';exp.addEventListener('submit',e=>{e.preventDefault();const out=$('[data-expectancy-result]',exp);try{const d=new FormData(exp),value=window.TradeMath.expectancy(...['rate','win','loss','cost'].map(k=>Number(d.get(k))));out.textContent=`Illustrative net expectancy: ${num(value)} per trade.\n${value<0?'Costs and losing outcomes outweigh the assumed wins.':'This assumed average is not a guarantee or evidence of a real edge.'}`;out.dataset.error='false';}catch(e){out.textContent=e.message;out.dataset.error='true';}});}
const journal=$('[data-journal-form]',root);if(journal&&!journal.dataset.ready){journal.dataset.ready='true';const notes=$('textarea',journal),saved=read(journalKey);if(typeof saved?.text==='string')notes.value=saved.text.slice(0,10000);journal.addEventListener('submit',e=>{e.preventDefault();const ok=save(journalKey,{text:notes.value,updated:new Date().toISOString()});$('[data-journal-status]',journal).textContent=ok?'Your notes are saved on this browser.':'Storage is unavailable. Use Download my notes to keep a copy.';});$('[data-export-journal]',journal).addEventListener('click',()=>{const blob=new Blob(['Trade Zuko — personal study notes\n'+new Date().toISOString()+'\n\n'+notes.value],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Trade-Zuko-Study-Notes.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
const payoff=$('[data-payoff-lab]',root);if(payoff&&!payoff.dataset.ready){payoff.dataset.ready='true';const select=$('#z-strategy',payoff),range=$('#z-underlying',payoff);function draw(){const s=window.TradeMath.strategies.find(v=>v.id===select.value)||window.TradeMath.strategies[0],price=Number(range.value);const values=Array.from({length:121},(_,i)=>({x:700+i*5,y:s.fn(700+i*5)}));const lo=Math.min(-30,...values.map(v=>v.y)),hi=Math.max(30,...values.map(v=>v.y)),pad=(hi-lo)*.12;const ymin=lo-pad,ymax=hi+pad,px=x=>60+(x-700)/600*655,py=y=>320-(y-ymin)/(ymax-ymin)*290;$('#z-payoff-path',payoff).setAttribute('d',values.map((v,i)=>(i?'L':'M')+px(v.x).toFixed(2)+' '+py(v.y).toFixed(2)).join(' '));$('#z-zero',payoff).setAttribute('d',`M60 ${py(0)}H715`);const dot=$('#z-payoff-dot',payoff);dot.setAttribute('cx',px(price));dot.setAttribute('cy',py(s.fn(price)));$('#z-y-max',payoff).textContent=num(hi);$('#z-y-min',payoff).textContent=num(lo);$('#z-underlying-value',payoff).textContent=num(price);$('[data-strategy-name]',payoff).textContent=s.name;$('[data-strategy-legs]',payoff).textContent=s.legs;$('[data-payoff-result]',payoff).textContent=num(s.fn(price));$('[data-payoff-loss]',payoff).textContent=num(s.loss);$('[data-payoff-gain]',payoff).textContent=s.gain;$('[data-payoff-break]',payoff).textContent=s.breakeven;$('.z-payoff-chart',payoff).setAttribute('aria-label',`${s.name}: hypothetical expiry P/L at settlement ${price} is ${s.fn(price)} per unit, before costs.`);}select.addEventListener('change',draw);range.addEventListener('input',draw);draw();}
const scenes=all('.z-card,.z-hero-visual,.z-app-promo,.world-section',root);if('IntersectionObserver'in window){visualObserver?.disconnect();visualObserver=new IntersectionObserver(entries=>entries.forEach(e=>e.target.dataset.visualIdle=String(!e.isIntersecting)),{rootMargin:'80px'});scenes.forEach(el=>visualObserver.observe(el));}
}
window.TradeLearning={init};init();
})();
